name: kaistrap
description: A library for bootstrapping KaiHeiLa with KaiHax
version: 1.0.0
platforms: 
  windows:
  linux:
  macos:

homepage: https://github.com/KaiHax/

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  http: ^0.13.4
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
